/**
 * i18n for the center. Plain objects; the catalog carries its own zh/en text.
 * The host locale id looks like "zh" / "zh-CN" / "en" ...; anything starting with "zh" gets Chinese.
 */
export const STR = {
  zh: {
    title: 'VibeDev 插件中心', preview: '预览',
    tabAll: '全部', tabInstalled: '已安装', tabUpdates: '可更新', tabCommunity: '社区插件',
    about: '关于插件中心',
    introTitle: 'VibeDev 团队出品的插件，集中在这里',
    introLead: '一个入口了解、安装和管理 VibeDev 官方插件。社区里更多的插件，请到插件市场。',
    f1t: '官方出品，说明写清楚', f1d: '每个插件由 VibeDev 维护；功能、费用、会读写什么、依赖什么，都写在卡片和详情里。',
    f2t: '一键安装，依赖自动处理', f2d: '点一次、确认一次，就自动完成「检查 → 安装 → 启用」；缺少的前置插件会一并装好。',
    f3t: '套装与迁移', f3d: '常用组合做成套装一键装齐；发现旧包名时，帮你按安全顺序切换到新包。',
    introMarketNo: '这里只收录 VibeDev 官方插件。想找社区里的其他插件，请用插件市场：',
    installMarket: '一键安装插件市场 →', openMarket: '打开插件市场 →',
    official: '官方插件', officialSub: (n) => `${n} 个 · 由 VibeDev 维护`,
    deps: '依赖与搭档', depsSub: '官方插件需要的、或值得搭配的社区插件；仅提供安装入口，本中心不审查其代码',
    install: '安装', installWithDeps: '安装（含依赖）', enabled: '已启用', disabled: '已停用', enable: '启用', manage: '管理 ▾',
    disable: '停用（保留数据）', uninstall: '卸载', details: '查看详情',
    updateTo: (v) => `更新到 ${v}`,
    needs: (names) => `需要 ${names}`, satisfied: '（已满足）', willInstall: '（未安装，会一并安装）',
    suiteInstall: '一键安装套装', suiteDone: '套装已全部安装',
    suiteWill: (n, have, size) => `将安装 ${n} 个插件（已装 ${have} 个）· ${size}`,
    tagOfficial: '官方', tagCommunity: '社区插件', tagNeedsAccount: '需要 VibeDev 账号', tagPaid: '按用量计费',
    tagNeedsHost02: '需要 VibeDev / DSH 0.2.x', tagNeedsSidebar: '需要 Better Sidebar', tagDependency: '前置依赖', tagCompanion: '推荐搭档', tagTested: '已测试',
    does: '能做什么', needsH: '需要什么', prereq: '前置插件', partners: '搭档（可选）', size: '体积', none: '无',
    capsH: '权限与费用', sourceH: '来源与审查', source: '来源', review: '审查', compat: '兼容性',
    officialSrc: 'VibeDev 官方', communitySrc: (a) => `社区插件 · ${a}`,
    officialReview: '由 VibeDev 团队维护', notReviewed: '本中心未审查其代码',
    reviewedBy: (v, d) => `已在 VibeDev 测试 · 版本 ${v} · ${d}`,
    compatS: { verified: '已验证', likely: '可能兼容', unknown: '未知', incompatible: '不兼容' },
    manualH: '手动安装', manualNote: 'VibeDev 桌面版的命令是 vibedev-app plugin --profile desktop add <包名>；安装前请先完全退出应用。',
    linksH: '链接', repo: 'GitHub', npm: 'npm',
    footMore: '想找更多社区插件？', footFeedback: '反馈问题', footCatalog: (d) => `目录版本 ${d} · 来自随包快照`,
    confirmInstall: (n, upd) => `确认并${upd ? '更新' : '安装'} ${n} 个插件`, cancel: '取消', back: '返回',
    willInstallN: (n, skip, size) => `将安装 ${n} 个插件${skip ? `，已安装的 ${skip} 个自动跳过` : ''} · ${size}`,
    willUpdateN: (n, size) => `将更新 ${n} 个插件 · ${size}`,
    alreadyInstalled: '已安装，跳过', afterUpdateRefresh: '更新后需要重启 VibeDev 才会生效',
    acctTitle: '需要 VibeDev 账号，按用量计费',
    acctBody: (names) => `${names}：在 VibeDev 里直接使用你已登录的账号；在 DSH 里首次使用时由 Agent 引导登录。安装本身不收费。`,
    freshNote: '这个版本刚发布，包管理器默认会等一天再放行；插件中心会按确切版本安装。更新不会改动你的项目文件和插件设置。',
    stepsH: '将要执行的操作（点击展开）',
    stepsFoot: '通过 VibeDev 官方插件管理器完成。只会处理上面列出的插件，之后可随时停用或卸载。',
    consent: (upd) => `点击「确认并${upd ? '更新' : '安装'}」即同意处理以上插件`,
    installing: '正在安装', progress: (d, n) => `${d} / ${n} 完成 · 请保持页面打开`,
    stWait: '等待', stInspect: '检查中', stInstall: '下载与安装', stEnable: '启用', stDone: '已启用', stFail: '失败', stHold: '待你确认', stSkip: '已安装',
    logH: '安装日志', cancelInstall: '取消安装', cancelHintOk: '可以取消；已装好的插件会保留', cancelHintLate: '已进入应用阶段，无法取消',
    doneTitle: '安装完成', doneSub: (d, n) => `${d} / ${n} 个插件已装好`,
    doneHead: (d) => `已安装并启用 ${d} 个插件`, doneRefresh: '刷新页面后即可使用。',
    nextH: '接下来',
    nextFilm: '打开任意会话的右侧栏，在「开始」页点「剧本」「分镜画布」「导演台」。',
    nextMedia: 'VibeDev 媒体生成：在 VibeDev 里直接用你已登录的账号；对 Agent 说「生成一张…」即可。',
    nextViewer: '在右侧栏点开 mp4、wav 或 html 文件就能直接预览；右侧栏「+」菜单里有「媒体画廊」。',
    nextMarket: '插件市场在这里的「社区插件」标签页里使用；它也会出现在设置里。',
    nextMarketHint: '想找社区里的更多插件？回到首页「依赖与搭档」，可以一键安装插件市场。',
    refreshLater: '稍后刷新', refreshNow: '立即刷新页面', gotIt: '知道了',
    restartTitle: '安装完成，需要重启', restartHead: '已安装，但需要重启 VibeDev 才能生效',
    restartBody: (n) => `${n} 个插件已写入配置。插件中心不会替你重启应用；请先保存手头的工作，再完全退出并重新打开。`,
    failTitle: '安装未完成',
    fNetworkT: '无法下载插件', fNetworkB: '已依次尝试 npm 官方源和国内镜像，都没有连上。请检查网络或代理后重试。',
    fBuildsT: '这个插件的依赖需要执行构建脚本', fBuildsB: (names) => `待你决定的包：${names}。构建脚本会以你的用户权限运行命令，请只在信任来源时允许。`,
    fIncompatT: '当前 VibeDev 版本不满足要求', fIncompatB: (s) => `${s}已拦截安装，没有下载任何内容。`,
    fNotFoundT: '在 npm 上找不到这个版本', fNotFoundB: '目录里登记的版本可能已被撤回或还没同步到镜像。请稍后重试，或到 GitHub 反馈。',
    fMismatchT: '已拦截：npm 返回的内容和目录不一致', fMismatchB: (d) => `为了安全，没有安装。${d}`,
    fExemptT: '包管理器的「新版本冷却期」拦住了所有安装和卸载', fExemptB: (c, when) => `${c ? c + ' ' : ''}发布不足一天，pnpm 默认不放行。这会影响所有插件的安装和卸载，直到${when ? ' ' + when + ' ' : ''}冷却期结束。`,
    fBusyT: '现在无法操作', fBusyB: '有会话正在运行，或这个插件正被使用。请先结束相关会话再试。',
    fRefusedT: '插件管理器拒绝了这个请求', fFailedT: '安装没有成功', fFailedB: '插件管理器没有给出更多信息，详情见日志。',
    keptDone: (n) => `已完成的 ${n} 个插件会保留；`, noChangeFail: '失败的插件没有改动你的插件配置。', noChangeHold: '你确认之前没有改动插件配置。',
    installedNotEnabled: '插件已装好，但启用失败；可以在设置的插件页手动启用。',
    retry: '重试', approveRetry: '允许这些脚本并重试', skipThis: '跳过此插件', copyCmd: '复制安装命令', later: '稍后再试', seeCompat: '查看兼容说明',
    uncertainT: '没能确认结果', uncertainB: '和插件管理器的连接中断了，安装可能已经完成。点「重新检查」查看实际状态。', recheck: '重新检查',
    migrateTitle: (old) => `检测到旧版插件 ${old}`,
    migrateBody: (old, nw) => `它已改名为 ${nw}。两者不能同时启用，否则可能互相冲突。`,
    migrateOrder: '切换顺序：安装新包但先不启用 → 停用旧包 → 启用新包 → 确认可用后再卸载旧包。', migrateBtn: '一键切换',
    migrating: '正在切换', migDone: '已切换到新包，旧包已卸载。', migHalf: '已切换到新包；旧包已停用但没能卸载，可稍后在插件页手动卸载。',
    migRestored: '没能启用新包，已把旧包重新启用，你的功能不受影响。',
    halfRemovedT: '插件已被停用，但没有卸载干净', halfRemovedB: '它现在是「已停用、仍安装」的状态。可以重新启用，或解决问题后重试卸载。', reenable: '重新启用', retryUninstall: '重试卸载',
    communityEmptyT: '社区里有大量插件，需要先安装插件市场',
    communityEmptyB: '插件市场是社区维护的第三方插件（dshmarket，MIT 许可）。装好后，可以直接在这个标签页里浏览、搜索和安装社区插件。',
    communityNote: '约 4 MB · 会联网读取公共插件目录 · 由 dsh-market 团队维护，本中心不审查其代码',
    communityViaMarket: '由插件市场 dshmarket 提供', communityAbout: '关于插件市场',
    communityNoEmbed: '插件市场已安装，但没能在这里嵌入它的界面。请在设置里打开「插件市场」。',
    allUpToDate: '所有官方插件都是最新版本', nothingInstalled: '还没有安装任何官方插件',
    loadFail: '没能读取已安装的插件', loadFailB: '插件管理器暂时不可用。仍可使用下面的「复制安装命令」手动安装。',
    noManager: '这个环境没有提供插件管理器，无法一键安装。请用详情里的命令手动安装。',
    sizeSmall: '很小',
  },
  en: {
    title: 'VibeDev Plugin Center', preview: 'Preview',
    tabAll: 'All', tabInstalled: 'Installed', tabUpdates: 'Updates', tabCommunity: 'Community',
    about: 'About',
    introTitle: 'Plugins from the VibeDev team, in one place',
    introLead: 'One place to learn about, install and manage the official VibeDev plugins. For the wider community, use the plugin market.',
    f1t: 'Official, and spelled out', f1d: 'Every plugin is maintained by VibeDev. What it does, what it costs, what it reads and writes, and what it needs are all on the card and in the details.',
    f2t: 'One click, dependencies handled', f2d: 'Click once, confirm once, and it runs "check → install → enable". Missing prerequisites are installed with it.',
    f3t: 'Suites and migration', f3d: 'Common combinations come as a suite you install in one go; if an old package name is found, we switch you to the new one in a safe order.',
    introMarketNo: 'Only official VibeDev plugins are listed here. For community plugins, use the plugin market: ',
    installMarket: 'Install the plugin market →', openMarket: 'Open the plugin market →',
    official: 'Official plugins', officialSub: (n) => `${n} · maintained by VibeDev`,
    deps: 'Prerequisites and companions', depsSub: 'Community plugins that official ones need or pair well with; install link only, this center does not review their code',
    install: 'Install', installWithDeps: 'Install (with dependencies)', enabled: 'Enabled', disabled: 'Disabled', enable: 'Enable', manage: 'Manage ▾',
    disable: 'Disable (keep data)', uninstall: 'Uninstall', details: 'Details',
    updateTo: (v) => `Update to ${v}`,
    needs: (names) => `Needs ${names}`, satisfied: ' (satisfied)', willInstall: ' (not installed, will be added)',
    suiteInstall: 'Install the suite', suiteDone: 'Suite fully installed',
    suiteWill: (n, have, size) => `Will install ${n} plugin(s) (${have} already installed) · ${size}`,
    tagOfficial: 'Official', tagCommunity: 'Community', tagNeedsAccount: 'Needs a VibeDev account', tagPaid: 'Pay per use',
    tagNeedsHost02: 'Needs VibeDev / DSH 0.2.x', tagNeedsSidebar: 'Needs Better Sidebar', tagDependency: 'Prerequisite', tagCompanion: 'Companion', tagTested: 'Tested',
    does: 'What it does', needsH: 'What it needs', prereq: 'Prerequisites', partners: 'Pairs with (optional)', size: 'Size', none: 'None',
    capsH: 'Permissions and cost', sourceH: 'Source and review', source: 'Source', review: 'Review', compat: 'Compatibility',
    officialSrc: 'VibeDev official', communitySrc: (a) => `Community plugin · ${a}`,
    officialReview: 'Maintained by the VibeDev team', notReviewed: 'Its code is not reviewed by this center',
    reviewedBy: (v, d) => `Tested on VibeDev · version ${v} · ${d}`,
    compatS: { verified: 'Verified', likely: 'Likely compatible', unknown: 'Unknown', incompatible: 'Incompatible' },
    manualH: 'Install by hand', manualNote: 'On VibeDev desktop the command is vibedev-app plugin --profile desktop add <package>; quit the app completely first.',
    linksH: 'Links', repo: 'GitHub', npm: 'npm',
    footMore: 'Looking for more community plugins? ', footFeedback: 'Feedback', footCatalog: (d) => `Catalog ${d} · bundled snapshot`,
    confirmInstall: (n, upd) => `Confirm and ${upd ? 'update' : 'install'} ${n} plugin(s)`, cancel: 'Cancel', back: 'Back',
    willInstallN: (n, skip, size) => `Will install ${n} plugin(s)${skip ? `; ${skip} already installed are skipped` : ''} · ${size}`,
    willUpdateN: (n, size) => `Will update ${n} plugin(s) · ${size}`,
    alreadyInstalled: 'Already installed, skipped', afterUpdateRefresh: 'Takes effect after restarting VibeDev',
    acctTitle: 'Needs a VibeDev account, billed by use',
    acctBody: (names) => `${names}: inside VibeDev it uses the account you are already signed in with; in DSH the agent walks you through sign-in on first use. Installing itself is free.`,
    freshNote: 'This version was just published and the package manager normally waits a day before allowing it; the center installs the exact version. Updating does not touch your project files or plugin settings.',
    stepsH: 'What will run (click to expand)',
    stepsFoot: 'Done through the VibeDev plugin manager. Only the plugins listed above are touched, and you can disable or remove them any time.',
    consent: (upd) => `Clicking "Confirm and ${upd ? 'update' : 'install'}" means you agree to process the plugins above`,
    installing: 'Installing', progress: (d, n) => `${d} / ${n} done · keep this page open`,
    stWait: 'Waiting', stInspect: 'Checking', stInstall: 'Downloading', stEnable: 'Enabling', stDone: 'Enabled', stFail: 'Failed', stHold: 'Needs your OK', stSkip: 'Installed',
    logH: 'Install log', cancelInstall: 'Cancel install', cancelHintOk: 'You can cancel; plugins already installed are kept', cancelHintLate: 'Already applying, cannot cancel',
    doneTitle: 'Install complete', doneSub: (d, n) => `${d} / ${n} plugin(s) installed`,
    doneHead: (d) => `Installed and enabled ${d} plugin(s)`, doneRefresh: 'Reload the page to start using them.',
    nextH: 'Next',
    nextFilm: 'Open the right sidebar in any session and use "Script", "Storyboard" or "Director" on the start page.',
    nextMedia: 'VibeDev Media: inside VibeDev it uses your signed-in account; just ask the agent to "generate an image of…".',
    nextViewer: 'Open an mp4, wav or html file in the right sidebar to preview it; the sidebar "+" menu has "Media gallery".',
    nextMarket: 'The plugin market lives in the "Community" tab here; it also appears in Settings.',
    nextMarketHint: 'Want more community plugins? Back on the home page, "Prerequisites and companions" installs the plugin market in one click.',
    refreshLater: 'Reload later', refreshNow: 'Reload now', gotIt: 'Got it',
    restartTitle: 'Installed, restart needed', restartHead: 'Installed, but VibeDev must restart to take effect',
    restartBody: (n) => `${n} plugin(s) were written to your configuration. The center will not restart the app for you; save your work, then quit completely and reopen.`,
    failTitle: 'Install not finished',
    fNetworkT: 'Could not download the plugin', fNetworkB: 'The official npm registry and the China mirror were both tried and neither answered. Check your network or proxy and retry.',
    fBuildsT: "This plugin's dependencies need to run build scripts", fBuildsB: (names) => `Packages waiting for your decision: ${names}. Build scripts run commands with your user's permissions; allow them only if you trust the source.`,
    fIncompatT: 'This VibeDev version does not meet the requirements', fIncompatB: (s) => `${s}Install was blocked and nothing was downloaded.`,
    fNotFoundT: 'That version was not found on npm', fNotFoundB: 'The version in the catalog may have been withdrawn or not yet mirrored. Retry later, or report it on GitHub.',
    fMismatchT: 'Blocked: what npm returned does not match the catalog', fMismatchB: (d) => `Nothing was installed, for safety. ${d}`,
    fExemptT: "The package manager's new-release cooldown is blocking all installs and uninstalls", fExemptB: (c, when) => `${c ? c + ' ' : ''}was published less than a day ago and pnpm does not allow it by default. This affects installing and removing every plugin until${when ? ' ' + when + ',' : ''} when the cooldown ends.`,
    fBusyT: 'Cannot do that right now', fBusyB: 'A session is running or the plugin is in use. End the related sessions and try again.',
    fRefusedT: 'The plugin manager refused this request', fFailedT: 'The install did not succeed', fFailedB: 'The plugin manager gave no further detail; see the log.',
    keptDone: (n) => `The ${n} plugin(s) already finished are kept; `, noChangeFail: 'the failed plugin did not change your plugin configuration.', noChangeHold: 'nothing in your plugin configuration changes until you confirm.',
    installedNotEnabled: 'The plugin is installed but enabling failed; you can enable it by hand on the Plugins page in Settings.',
    retry: 'Retry', approveRetry: 'Allow these scripts and retry', skipThis: 'Skip this plugin', copyCmd: 'Copy install command', later: 'Try later', seeCompat: 'See compatibility notes',
    uncertainT: 'Could not confirm the result', uncertainB: 'The connection to the plugin manager dropped; the install may have finished. Click "Check again" to see the real state.', recheck: 'Check again',
    migrateTitle: (old) => `Old plugin ${old} detected`,
    migrateBody: (old, nw) => `It has been renamed to ${nw}. They cannot both be enabled or they may conflict.`,
    migrateOrder: 'Switch order: install the new one disabled → disable the old one → enable the new one → remove the old one once it works.', migrateBtn: 'Switch now',
    migrating: 'Switching', migDone: 'Switched to the new package and removed the old one.', migHalf: 'Switched to the new package; the old one is disabled but could not be removed, remove it later on the Plugins page.',
    migRestored: 'Could not enable the new package, so the old one was turned back on; nothing you use is affected.',
    halfRemovedT: 'The plugin was disabled but not fully removed', halfRemovedB: 'It is now "disabled but still installed". You can enable it again, or fix the cause and retry removal.', reenable: 'Enable again', retryUninstall: 'Retry removal',
    communityEmptyT: 'The community has a lot of plugins; install the plugin market first',
    communityEmptyB: 'The plugin market is a community-maintained third-party plugin (dshmarket, MIT). Once installed, you can browse, search and install community plugins right in this tab.',
    communityNote: 'About 4 MB · reads the public plugin catalog online · maintained by the dsh-market team; this center does not review its code',
    communityViaMarket: 'Provided by the plugin market (dshmarket)', communityAbout: 'About the plugin market',
    communityNoEmbed: 'The plugin market is installed but its interface could not be embedded here. Open "Plugin Market" in Settings.',
    allUpToDate: 'All official plugins are up to date', nothingInstalled: 'No official plugin is installed yet',
    loadFail: 'Could not read the installed plugins', loadFailB: 'The plugin manager is unavailable for now. You can still install by hand with "Copy install command".',
    noManager: 'This environment does not provide a plugin manager, so one-click install is unavailable. Use the command in the details instead.',
    sizeSmall: 'tiny',
  },
}

export const pick = (localeId) => (String(localeId ?? '').toLowerCase().startsWith('zh') ? 'zh' : 'en')
export const L = (obj, lang) => (obj && typeof obj === 'object' ? obj[lang] ?? obj.en ?? obj.zh : obj)

export function fmtSize(kb) {
  if (kb >= 1024) return `${(kb / 1024).toFixed(kb >= 10240 ? 0 : 1)} MB`
  return `${kb < 100 ? Math.max(kb / 1024, 0.01).toFixed(2) : (kb / 1024).toFixed(1)} MB`
}
